module.exports = {
  apps: [
    {
      name: 'sims-backend',
      script: 'dist/main.js',
      cwd: './server',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      env_file: './.env',
      max_memory_restart: '512M',
      min_uptime: 10000,
      max_restarts: 10,
      restart_delay: 5000,
      watch: false,
      error_file: './logs/backend-error.log',
      out_file: './logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'sims-frontend',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      max_memory_restart: '1G',
      min_uptime: 10000,
      max_restarts: 5,
      restart_delay: 5000,
      watch: false,
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
